from odoo import api,fields,models,tools,_

class OrigineCountries(models.Model):
    _name = "origin.select"
    _description = "Countries selection for folder managments"
    origine_contries = fields.Selection([
        ("Afghanistan","Afghanistan"),
        ("Albania","Albania"),
        ("Algeria","Algeria"),
        ("Angola","Angola"),
        ("Argentina","Argentina"),
        ("Australia","Australia"),
        ("Austria","Austria"),
        ("BAHREIN","BAHREIN"),
        ("Bangladesh","Bangladesh"),
        ("Belgium","Belgium"),
        ("Benin","Benin"),
        ("Bolivia","Bolivia"),
        ("Botswana","Botswana"),
        ("Brazil","Brazil"),
        ("Bulgaria","Bulgaria"),
        ("BURKINA FASO","BURKINA FASO"),
        ("Cabo Verde","Cabo Verde"),
        ("CAMBODGE","CAMBODGE"),
        ("Cameroon","Cameroon"),
        ("Canada","Canada"),
        ("CHILI","CHILI"),
        ("China","China"),
        ("Colombia","Colombia"),
        ("Communaute europeenne","Communaute europeenne"),
        ("Congo","Congo"),
        ("Congo (IGnshasa)","Congo (IGnshasa)"),
        ("COSTA RICA","COSTA RICA"),
        ("Cote divoire","Cote divoire"),
        ("Croatia","Croatia"),
        ("Czech Republic","Czech Republic"),
        ("Denmark","Denmark"),
        ("Djibouti","Djibouti"),
        ("Dominica","Dominica"),
        ("Dominican Republic","Dominican Republic"),
        ("Ecuador","Ecuador"),
        ("Egypt","Egypt"),
        ("El Salvador","El Salvador"),
        ("Estonia","Estonia"),
        ("Ethiopia","Ethiopia"),
        ("Finland","Finland"),
        ("France","France"),
        ("Gabon","Gabon"),
        ("Georgia","Georgia"),
        ("GERMANY","GERMANY"),
        ("GHANA","GHANA"),
        ("Greece","Greece"),
        ("Guinea","Guinea"),
        ("Haiti","Haiti"),
        ("HONDURAS","HONDURAS"),
        ("Hong Kong","Hong Kong"),
        ("Hungary","Hungary"),
        ("ndia","ndia"),
        ("ndonesia","ndonesia"),
        ("ran","ran"),
        ("raq","raq"),
        ("reland","reland"),
        ("srael","srael"),
        ("New Zealand","New Zealand"),
        ("Niger","Niger"),
        ("Nigeria","Nigeria"),
        ("NORFOLK ISLAND","NORFOLK ISLAND"),
        ("Norway","Norway"),
        ("Oman","Oman"),
        ("PAKISTAN","PAKISTAN"),
        ("PARAGUAY","PARAGUAY"),
        ("PARK-OHIO INDUSTRIES","PARK-OHIO INDUSTRIES"),
        ("PAYS-BAS","PAYS-BAS"),
        ("Philippines","Philippines"),
        ("Poland","Poland"),
        ("Portugal","Portugal"),
        ("Qatar","Qatar"),
        ("Republique de Maurice","Republique de Maurice"),
        ("Romania","Romania"),
        ("Russia","Russia"),
        ("Rwanda","Rwanda"),
        ("Saudi Arabia","Saudi Arabia"),
        ("SENEGAL","SENEGAL"),
        ("SERBIA","SERBIA"),
        ("SERBIE","SERBIE"),
        ("Singapore","Singapore"),
        ("SLOVAKIA","SLOVAKIA"),
        ("Slovenia","Slovenia"),
        ("Somalia","Somalia"),
        ("South Africa","South Africa"),
        ("Spain","Spain"),
        ("S main","S main"),
        ("Sri Lanka","Sri Lanka"),
        ("Sudan","Sudan"),
        ("suisse","suisse"),
        ("SWAZILAND","SWAZILAND"),
        ("Sweden","Sweden"),
        ("SWITZERLAND","SWITZERLAND"),
        ("Syria","Syria"),
        ("Taiwan","Taiwan"),
        ("Tanzania","Tanzania"),
        ("Tenitoire palestinien occupe","Tenitoire palestinien occupe"),
        ("Thailand","Thailand"),
        ("TOGO","TOGO"),
        ("Tunisia","Tunisia"),
        ("Turkey","Turkey"),
        ("UE","UE"),
        ("UKRAINE","UKRAINE"),
        ("United Nab Emirates","United Nab Emirates"),
        ("United Kingdom","United Kingdom"),
        ("United States","United States"),
        ("Uruguay","Uruguay"),
        ("Venezuela","Venezuela"),
        ("Vietnam","Vietnam"),
        ("Yemen","Yemen"),
        ("Zambia","Zambia"),
        ("Zimbabwe","Zimbabwe"),
        ("ZONE FRANCHE","ZONE FRANCHE")
     ],string="Origine"
    )