from odoo import api,fields,models,tools,_

class Transporteur(models.Model):
    _name = 'transporter'
    _rec_name = 'transporter_list'
    _description = 'transporteur for folder managment'
    transporter_list = fields.Selection([
        ("ANDALOSSI", "ANDALOSSI"),
        ("CCCM TRANSPORT", "CCCM TRANSPORT"),
        ("2A INTER", "2A INTER"),
        ("365 LOGISTICS", "365 LOGISTICS"),
        ("4TL MED TRANSIT", "4TL MED TRANSIT"),
        ("A RIGHT TRANS", "A RIGHT TRANS"),
        ("A.M.R TRANS", "A.M.R TRANS"),
        ("A7", "A7"),
        ("ABENDIR TRANS", "ABENDIR TRANS"),
        ("ABRATEX", "ABRATEX"),
        ("ACCESS", "ACCESS"),
        ("ACCIONA", "ACCIONA"),
        ("ACCUERDO TRANS", "ACCUERDO TRANS"),
        ("ACOMAR", "ACOMAR"),
        ("acome", "acome"),
        ("ACOTRAL", "ACOTRAL"),
        ("ACX Advanced Cargo Express", "ACX Advanced Cargo Express"),
        ("AD LOGISTIQUE", "AD LOGISTIQUE"),
        ("ADAM", "ADAM"),
        ("adam std", "adam std"),
        ("ADAMIR TRANS", "ADAMIR TRANS"),
        ("ADATRA", "ADATRA"),
        ("ADDIXO", "ADDIXO"),
        ("ADI-SAM LOGISTIC", "ADI-SAM LOGISTIC"),
        ("ADUANASALIE", "ADUANASALIE"),
        ("ADUANERAS LEON", "ADUANERAS LEON"),
        ("AFRICAN DEMIN", "AFRICAN DEMIN"),
        ("AFRICONTAINER", "AFRICONTAINER"),
        ("AFRIQUE EUROPE FRET", "AFRIQUE EUROPE FRET"),
        ("BERNNEN", "BERNNEN"),
        ("BETA TRANS SARL", "BETA TRANS SARL"),
        ("BEYA TRANS", "BEYA TRANS"),
        ("BGH LOGISTIQUE", "BGH LOGISTIQUE"),
        ("BIG INTER GLOBE", "BIG INTER GLOBE"),
        ("BIM5TANS", "BIM5TANS"),
        ("BING INTER", "BING INTER"),
        ("BINWA", "BINWA"),
        ("BIOTRANS", "BIOTRANS"),
        ("BOLIPESK", "BOLIPESK"),
        ("BOLlore", "BOLlore"),
        ("BOLLORE TRANSPORT 8 LOGISTICS MAF", "BOLLORE TRANSPORT 8 LOGISTICS MAF"),
        ("BOUADOUL TRANS", "BOUADOUL TRANS"),
        ("BRENNAN CARGO", "BRENNAN CARGO"),
        ("BUSINESS COMMERCIAL MARTIME CMG", "BUSINESS COMMERCIAL MARTIME CMG"),
        ("CA TECHNIQUE", "CA TECHNIQUE"),
        ("CALSINA CARRE MAGHREB", "CALSINA CARRE MAGHREB"),
        ("CALSINA Y CARRE", "CALSINA Y CARRE"),
        ("CAMPILLO PALMERA", "CAMPILLO PALMERA"),
        ("CANDIDO", "CANDIDO"),
        ("CAP CARGO", "CAP CARGO"),
        ("CAP MED LOGISTICS", "CAP MED LOGISTICS"),
        ("CARGO PARTNER", "CARGO PARTNER"),
        ("CARGO RIF", "CARGO RIF"),
        ("CASAUS MAROC", "CASAUS MAROC"),
        ("CASTAYA TRANS", "CASTAYA TRANS"),
        ("CAT MAROC", "CAT MAROC"),
        ("CBINCBON", "CBINCBON"),
        ("CEINDIJSTRIE", "CEINDIJSTRIE"),
        ("DADITRAC", "DADITRAC"),
        ("DAE TRANS", "DAE TRANS"),
        ("DAILA", "DAILA"),
        ("DAMANA", "DAMANA"),
        ("DANY TRANS", "DANY TRANS"),
        ("DAS LOGISTICS", "DAS LOGISTICS"),
        ("DASCHER", "DASCHER"),
        ("DBCONSULTING", "DBCONSULTING"),
        ("dbshenker", "dbshenker"),
        ("DECOEXSA", "DECOEXSA"),
        ("DELFINGEN", "DELFINGEN"),
        ("DELTA PREMIUM", "DELTA PREMIUM"),
        ("DEUTSCHLAND POIDS LOURDS", "DEUTSCHLAND POIDS LOURDS"),
        ("DEVELOPPEMENT BANSARD MAROC SAF", "DEVELOPPEMENT BANSARD MAROC SAF"),
        ("DGHOGHI TRANS", "DGHOGHI TRANS"),
        ("DHBB TRANS", "DHBB TRANS"),
        ("DHL", "DHL"),
        ("DHL EXPRESS", "DHL EXPRESS"),
        ("DHL LOGISTICS", "DHL LOGISTICS"),
        ("DHL MEAD", "DHL MEAD"),
        ("DIVERS", "DIVERS"),
        ("DREIER", "DREIER"),
        ("DREIER LOGISTIQUE MAROC", "DREIER LOGISTIQUE MAROC"),
        ("DSH", "DSH"),
        ("DSV", "DSV"),
        ("DTOO MAROC", "DTOO MAROC"),
        ("DUNAS TRANS", "DUNAS TRANS"),
        ("E.M TRANS MED", "E.M TRANS MED"),
        ("EAS", "EAS"),
        ("FRIO FRISUR", "FRIO FRISUR"),
        ("FRIO LAV LOGISTICS", "FRIO LAV LOGISTICS"),
        ("FRIO PINAZO S.L", "FRIO PINAZO S.L"),
        ("FRIO RAV LOGISTIC", "FRIO RAV LOGISTIC"),
        ("FRIO TANGER TRANS", "FRIO TANGER TRANS"),
        ("FRIO -TANJAH", "FRIO -TANJAH"),
        ("FRIOBAZA", "FRIOBAZA"),
        ("FRIOPINAZO", "FRIOPINAZO"),
        ("FRISUR JIMENEZ", "FRISUR JIMENEZ"),
        ("FTA", "FTA"),
        ("FUNCHAL TRANS", "FUNCHAL TRANS"),
        ("FUTUR TRANS ATLANTIC .:( FTA ,o", "FUTUR TRANS ATLANTIC .:( FTA ,o"),
        ("GA LOGISTIQUE", "GA LOGISTIQUE"),
        ("GALAXY LOGISTICS", "GALAXY LOGISTICS"),
        ("GARDIT", "GARDIT"),
        ("GARLAND", "GARLAND"),
        ("GCL", "GCL"),
        ("GD TRANS", "GD TRANS"),
        ("GECAM", "GECAM"),
        ("GEDETRANS EXPRESS MAROC SARL", "GEDETRANS EXPRESS MAROC SARL"),
        ("GEFCO", "GEFCO"),
        ("GEMAPRO", "GEMAPRO"),
        ("GEODIS", "GEODIS"),
        ("GEODIS FF MAROC", "GEODIS FF MAROC"),
        ("GEODIS WILSON MAROC", "GEODIS WILSON MAROC"),
        ("GERGONNE", "GERGONNE"),
        ("GERMANETTI", "GERMANETTI"),
        ("GHAFIR TRANS", "GHAFIR TRANS"),
        ("GHALTRANS", "GHALTRANS"),
        ("GHITA TRANS", "GHITA TRANS"),
        ("GLD", "GLD"),
        ("GLO", "GLO"),
        ("GLOBAL CARGO LOGISTIQUE", "GLOBAL CARGO LOGISTIQUE"),
        ("GLOBAL CARO LEADER", "GLOBAL CARO LEADER"),
        ("GLOBAL CHARGES SARL", "GLOBAL CHARGES SARL"),
        ("GLOBAL CONTAINER", "GLOBAL CONTAINER"),
        ("GLOBAL TRANS INTER", "GLOBAL TRANS INTER"),
        ("GLOBE MARINE", "GLOBE MARINE"),
        ("GLOBELINK", "GLOBELINK"),
        ("GLOBEX", "GLOBEX"),
        ("GLORY INTER TRANS", "GLORY INTER TRANS"),
        ("GLS", "GLS"),
        ("GLT", "GLT"),
        ("GNV", "GNV"),
        ("GOLOBAL CARGO LEADER GCL", "GOLOBAL CARGO LEADER GCL"),
        ("GONDRAND", "GONDRAND"),
        ("GR VALADE MAROC", "GR VALADE MAROC"),
        ("GRAVELEAU DACSHER", "GRAVELEAU DACSHER"),
        ("GROAT LORRY AND TRANSPORT", "GROAT LORRY AND TRANSPORT"),
        ("GROUP INTER FIVE", "GROUP INTER FIVE"),
        ("GROUP INTER FIVE SARL", "GROUP INTER FIVE SARL"),
        ("GROUP TRANS DU SUD", "GROUP TRANS DU SUD"),
        ("GROUPE A.TRANS MAROC", "GROUPE A.TRANS MAROC"),
        ("GROUPE G.R MAROC", "GROUPE G.R MAROC"),
        ("Groupe Logistique Develops", "Groupe Logistique Develops"),
        ("GROUPE MOHAMED NADI TRANSPORT S", "GROUPE MOHAMED NADI TRANSPORT S"),
        ("GROUPE SH TRANS", "GROUPE SH TRANS"),
        ("GROUPE STVA", "GROUPE STVA"),
        ("HRN TRANS", "HRN TRANS"),
        ("HSF LOGISTICS MAROC", "HSF LOGISTICS MAROC"),
        ("HTG EXPRESS", "HTG EXPRESS"),
        ("HUPE TRANSPORT LOGISTIQUE", "HUPE TRANSPORT LOGISTIQUE"),
        ("BERTRANS", "BERTRANS"),
        ("BN BATOTA TRANS", "BN BATOTA TRANS"),
        ("DEA MAROC", "DEA MAROC"),
        ("DEA MAROC SHIPPING", "DEA MAROC SHIPPING"),
        ("DI GROUP", "DI GROUP"),
        ("FRT TRANSPORT SARL", "FRT TRANSPORT SARL"),
        ("FS NEUTRAL MERITIME", "FS NEUTRAL MERITIME"),
        ("LIMAR TRANS SARL", "LIMAR TRANS SARL"),
        ("NAKI", "NAKI"),
        ("NAR TRANS sad", "NAR TRANS sad"),
        ("indumapac", "indumapac"),
        ("INTER GLOBAL AFRICA", "INTER GLOBAL AFRICA"),
        ("INTER LOAD SERVICE MAROC", "INTER LOAD SERVICE MAROC"),
        ("INTER TRANS", "INTER TRANS"),
        ("INTER TRANS-CO MAROC", "INTER TRANS-CO MAROC"),
        ("INTER WORLD TRANS", "INTER WORLD TRANS"),
        ("INTERFALE", "INTERFALE"),
        ("intedog", "intedog"),
        ("NTERMODAL LOGISTIQUE", "NTERMODAL LOGISTIQUE"),
        ("NTERNATIONALER", "NTERNATIONALER"),
        ("NTERPAOLI AFRIQUE", "NTERPAOLI AFRIQUE"),
        ("nTime", "nTime"),
        ("NTRA ZONE", "NTRA ZONE"),
        ("PSEN LOGISTICS", "PSEN LOGISTICS"),
        ("ROTTA", "ROTTA"),
        ("SAR", "SAR"),
        ("MNM TRANS", "MNM TRANS"),
        ("MODEEXPRESS", "MODEEXPRESS"),
        ("MONAUXILIAIRE GANNOUNE DISTRIBUT", "MONAUXILIAIRE GANNOUNE DISTRIBUT"),
        ("MORANCO", "MORANCO"),
        ("MOREXPRESS", "MOREXPRESS"),
        ("MOROCCO TRENDING SERVICES", "MOROCCO TRENDING SERVICES"),
        ("MOVE EXPRESS", "MOVE EXPRESS"),
        ("MOVMED TRANS", "MOVMED TRANS"),
        ("MP TRANSPORT", "MP TRANSPORT"),
        ("MR2A FRIO", "MR2A FRIO"),
        ("MSC", "MSC"),
        ("MSIMO TRANS", "MSIMO TRANS"),
        ("MTL MAROC", "MTL MAROC"),
        ("MTP MAROC", "MTP MAROC"),
        ("MULTITRANS", "MULTITRANS"),
        ("MYCS", "MYCS"),
        ("MYSK TRANSPORT SARL", "MYSK TRANSPORT SARL"),
        ("N2S TRANSPORT", "N2S TRANSPORT"),
        ("NAD-TRANS sad", "NAD-TRANS sad"),
        ("nakl anif", "nakl anif"),
        ("NASSAD TRANSPORT", "NASSAD TRANSPORT"),
        ("NASSAMER TR", "NASSAMER TR"),
        ("NAVIROC", "NAVIROC"),
        ("NCL", "NCL"),
        ("NECOTRANS MAROC", "NECOTRANS MAROC"),
        ("NEGOFRET", "NEGOFRET"),
        ("nejtrans", "nejtrans"),
        ("NEWSTEP LOGISTICS", "NEWSTEP LOGISTICS"),
        ("NEWWORLD", "NEWWORLD"),
        ("NEXT LINE LOGISTICS", "NEXT LINE LOGISTICS"),
        ("MAERSK", "MAERSK"),
        ("MAGHREB FREIGHT SYSTEMS", "MAGHREB FREIGHT SYSTEMS"),
        ("MAGHREB SOLUTIONS LOGISTICS", "MAGHREB SOLUTIONS LOGISTICS"),
        ("MAGNA EXPRESS", "MAGNA EXPRESS"),
        ("MAJDAOUI RAPIDE TRANS", "MAJDAOUI RAPIDE TRANS"),
        ("MALINTECH", "MALINTECH"),
        ("MAPA TRANS", "MAPA TRANS"),
        ("MARAY LOGISTICA S.L.", "MARAY LOGISTICA S.L."),
        ("MARBAR LOGISTICS", "MARBAR LOGISTICS"),
        ("MARCOATRANS", "MARCOATRANS"),
        ("MARCOTRAN", "MARCOTRAN"),
        ("MARGLORY", "MARGLORY"),
        ("MARINE MAROC", "MARINE MAROC"),
        ("MARLO FRIO", "MARLO FRIO"),
        ("MAROC EXPRESS", "MAROC EXPRESS"),
        ("MAROC MAUSA", "MAROC MAUSA"),
        ("MAROC TRANS CONSULTING", "MAROC TRANS CONSULTING"),
        ("MAROTRAN", "MAROTRAN"),
        ("MAROTRANS", "MAROTRANS"),
        ("MARSLOGISTIQUE", "MARSLOGISTIQUE"),
        ("MARSYS TRANS", "MARSYS TRANS"),
        ("MARTICO MAROC", "MARTICO MAROC"),
        ("MARTRANSIT", "MARTRANSIT"),
        ("MARYOU TRANS", "MARYOU TRANS"),
        ("MASSAKINE TRANSPORT", "MASSAKINE TRANSPORT"),
        ("MATILDA", "MATILDA"),
        ("Matranord", "Matranord"),
        ("matranord transport", "matranord transport"),
        ("MAYMANA TRANS", "MAYMANA TRANS"),
        ("MAYSSOUN TRANS", "MAYSSOUN TRANS"),
        ("OUSSALEM TRANSPORT", "OUSSALEM TRANSPORT"),
        ("OVERLAND TRADE AND SERVICES", "OVERLAND TRADE AND SERVICES"),
        ("OVERSEAS", "OVERSEAS"),
        ("OVI TRANS SPEDITION", "OVI TRANS SPEDITION"),
        ("P2M", "P2M"),
        ("PACIFIC CARGO", "PACIFIC CARGO"),
        ("PACTE MAROC", "PACTE MAROC"),
        ("PANTOJA", "PANTOJA"),
        ("PCPLUS", "PCPLUS"),
        ("PECARA TRANS", "PECARA TRANS"),
        ("PESCHAUD", "PESCHAUD"),
        ("PILOTAGE TRANS PLUS", "PILOTAGE TRANS PLUS"),
        ("PLASTIC OM", "PLASTIC OM"),
        ("POLYTRANS", "POLYTRANS"),
        ("POOL LINE SARL AU", "POOL LINE SARL AU"),
        ("PPI TRANS SARL", "PPI TRANS SARL"),
        ("PRO INTERNATIONAL", "PRO INTERNATIONAL"),
        ("PROEX DRINKS GROUP S.A.", "PROEX DRINKS GROUP S.A."),
        ("PROIN MAROC", "PROIN MAROC"),
        ("PROXAM", "PROXAM"),
        ("PUERTO MED TRANS", "PUERTO MED TRANS"),
        ("PUERTO TRANS", "PUERTO TRANS"),
        ("PUERTO TRANSIT", "PUERTO TRANSIT"),
        ("PWL", "PWL"),
        ("QAMAR TRANS", "QAMAR TRANS"),
        ("QUALITAIR", "QUALITAIR"),
        ("QUINTAS LUZ", "QUINTAS LUZ"),
        ("R.J.M LOGISTIQUE", "R.J.M LOGISTIQUE"),
        ("RACH KAM NEGOCE", "RACH KAM NEGOCE"),
        ("RACHINORD TRANS", "RACHINORD TRANS"),
        ("RTL MAROC", "RTL MAROC"),
        ("RUBI TRANS", "RUBI TRANS"),
        ("RUPA TRANS", "RUPA TRANS"),
        ("RUSIL TRANS", "RUSIL TRANS"),
        ("S.D.F.M LOGISTICS", "S.D.F.M LOGISTICS"),
        ("S.H EXPORT", "S.H EXPORT"),
        ("S.J TRANS", "S.J TRANS"),
        ("SIC SPA", "SIC SPA"),
        ("SAADANE", "SAADANE"),
        ("SABETRANS", "SABETRANS"),
        ("SAFMARINE", "SAFMARINE"),
        ("SAID SALMANI", "SAID SALMANI"),
        ("SAL SOUH TRANS SARL", "SAL SOUH TRANS SARL"),
        ("SAMSOODEEN", "SAMSOODEEN"),
        ("SAMUEL 8 OLIVER TRANS", "SAMUEL 8 OLIVER TRANS"),
        ("SAN JOSE-LOPEZ S.A.0", "SAN JOSE-LOPEZ S.A.0"),
        ("SAOUIR", "SAOUIR"),
        ("SAOURI TRANS", "SAOURI TRANS"),
        ("SARAJEVO TRANS", "SARAJEVO TRANS"),
        ("SAS DELTA LINE", "SAS DELTA LINE"),
        ("SATDH", "SATDH"),
        ("SATFI LOGISTICS", "SATFI LOGISTICS"),
        ("SATRANI", "SATRANI"),
        ("SAYAS TRANS", "SAYAS TRANS"),
        ("SAYFLAY TRANS", "SAYFLAY TRANS"),
        ("SB LOGISTICS", "SB LOGISTICS"),
        ("SBL", "SBL"),
        ("SBMZ TRANS", "SBMZ TRANS"),
        ("SCHENKER MAROC", "SCHENKER MAROC"),
        ("SCHLEMMER", "SCHLEMMER"),
        ("SCHUNK", "SCHUNK"),
        ("SDF LOGISTICS SARL", "SDF LOGISTICS SARL"),
        ("SDFM", "SDFM"),
        ("SDV MAROC", "SDV MAROC"),
        ("SE GREEN", "SE GREEN"),
        ("SEALAND", "SEALAND"),
        ("SERINFO LOGISTIQUE", "SERINFO LOGISTIQUE"),
        ("SERTRANS", "SERTRANS"),
        ("SERVICIOS MAGHREB", "SERVICIOS MAGHREB"),
        ("SERVIPORT MAROC sad", "SERVIPORT MAROC sad"),
        ("SESE", "SESE"),
        ("SEVEN LINE", "SEVEN LINE"),
        ("sews MFZ", "sews MFZ"),
        ("SGTTI", "SGTTI"),
        ("SHB TRANSPORT", "SHB TRANSPORT"),
        ("SHEYMI TRANS", "SHEYMI TRANS"),
        ("SHLEMMER", "SHLEMMER"),
        ("sie tanger", "sie tanger"),
        ("SIGMA TRANSPORT", "SIGMA TRANSPORT"),
        ("SINDO MAROC", "SINDO MAROC"),
        ("SJ TRANS", "SJ TRANS"),
        ("SJL MAGHREB sad", "SJL MAGHREB sad"),
        ("SKAY GRUE", "SKAY GRUE"),
        ("SKHIRI TRANS", "SKHIRI TRANS"),
        ("SKY LOGITRANS", "SKY LOGITRANS"),
        ("SLINE", "SLINE"),
        ("SLTM", "SLTM"),
        ("SLYMAG SARL", "SLYMAG SARL"),
        ("SMARTDESIGN", "SMARTDESIGN"),
        ("SOUVENIR TRANS", "SOUVENIR TRANS"),
        ("SOVAMADI", "SOVAMADI"),
        ("sovamep", "sovamep"),
        ("SOVEROC", "SOVEROC"),
        ("SPEEDY TRANSPORT 8 LOGISTICS", "SPEEDY TRANSPORT 8 LOGISTICS"),
        ("SPETRANS LOGISTIC", "SPETRANS LOGISTIC"),
        ("SPM", "SPM"),
        ("SR INDUS", "SR INDUS"),
        ("SR MALIDA", "SR MALIDA"),
        ("STAR-BR TRANS", "STAR-BR TRANS"),
        ("STATEMA", "STATEMA"),
        ("STC MA", "STC MA"),
        ("STE ATBIR FRIG SARL", "STE ATBIR FRIG SARL"),
        ("STE BELAROUSSI TRANS", "STE BELAROUSSI TRANS"),
        ("STE BEN SAAD", "STE BEN SAAD"),
        ("STE BIG INTER", "STE BIG INTER"),
        ("STE BIOTRANS", "STE BIOTRANS"),
        ("STE BOUADOUL TRANS", "STE BOUADOUL TRANS"),
        ("STE COOL LINE", "STE COOL LINE"),
        ("STE DIAE", "STE DIAE"),
        ("STE HD LOGISTIC SARL", "STE HD LOGISTIC SARL"),
        ("STE HIR TRANS SARL", "STE HIR TRANS SARL"),
        ("STE ISMAYOU TRANS", "STE ISMAYOU TRANS"),
        ("STE JANOU TRANS", "STE JANOU TRANS"),
        ("STE KHENIFRA-AMANA-TRANS SARL", "STE KHENIFRA-AMANA-TRANS SARL"),
        ("STE MARSYS TRANS", "STE MARSYS TRANS"),
        ("STE MOGAFISH", "STE MOGAFISH"),
        ("STE NAKL", "STE NAKL"),
        ("STE PIONEROS TOURS", "STE PIONEROS TOURS"),
        ("Ste SAFIvIAR trans", "Ste SAFIvIAR trans"),
        ("e", "e"),
        ("T.S.L", "T.S.L"),
        ("T.T.A.M", "T.T.A.M"),
        ("TAHAFABA LOGISTIC", "TAHAFABA LOGISTIC"),
        ("TAIBA DRAWN INTERNATIONAL", "TAIBA DRAWN INTERNATIONAL"),
        ("TANGER COURS", "TANGER COURS"),
        ("Tanger Courses", "Tanger Courses"),
        ("TANGER EXPRESS", "TANGER EXPRESS"),
        ("TARROS MAROC", "TARROS MAROC"),
        ("TBC", "TBC"),
        ("TCL", "TCL"),
        ("TDT", "TDT"),
        ("TECA PRIME", "TECA PRIME"),
        ("TECHMAC", "TECHMAC"),
        ("teknia", "teknia"),
        ("TELE TRANS", "TELE TRANS"),
        ("TELEDYNE", "TELEDYNE"),
        ("TGS MAROC", "TGS MAROC"),
        ("thaziri trans", "thaziri trans"),
        ("THE WEIGHT LOGISTICS", "THE WEIGHT LOGISTICS"),
        ("TIM INTER FRIGO", "TIM INTER FRIGO"),
        ("TIMALLIANCE TRANSPORTS", "TIMALLIANCE TRANSPORTS"),
        ("TIMAR SARL", "TIMAR SARL"),
        ("TIME TRANS SARL", "TIME TRANS SARL"),
        ("TIP PESCHAUD", "TIP PESCHAUD"),
        ("TIRMAIAMAROC", "TIRMAIAMAROC"),
        ("TIRSOINTERNATION", "TIRSOINTERNATION"),
        ("TIWLI TRANS", "TIWLI TRANS"),
        ("TIZI TRANS2018.S.L", "TIZI TRANS2018.S.L"),
        ("TLS", "TLS"),
        ("TNA CARGO", "TNA CARGO"),
        ("UNISOURCE", "UNISOURCE"),
        ("UNIVERSAL FREIGHT SERVICES", "UNIVERSAL FREIGHT SERVICES"),
        ("UNIVERSAL SHIPPING", "UNIVERSAL SHIPPING"),
        ("UNLIMITED TRANSPORT", "UNLIMITED TRANSPORT"),
        ("UPS", "UPS"),
        ("V CTORYS LOGISTIQUE MAROC", "V CTORYS LOGISTIQUE MAROC"),
        ("Valdeme", "Valdeme"),
        ("VALIENTE", "VALIENTE"),
        ("VALORISE", "VALORISE"),
        ("VAT LOGISTICA", "VAT LOGISTICA"),
        ("VDM EXPORTACIONES", "VDM EXPORTACIONES"),
        ("VECTORYS", "VECTORYS"),
        ("VH TRANSPORT", "VH TRANSPORT"),
        ("VIDA TRANS", "VIDA TRANS"),
        ("WARREN TRANS", "WARREN TRANS"),
        ("WCS", "WCS"),
        ("WEC LINES", "WEC LINES"),
        ("WE-LOGISTICS", "WE-LOGISTICS"),
        ("WFS", "WFS"),
        ("WIDEM LOGISTIQUE", "WIDEM LOGISTIQUE"),
        ("XF TRANS SARL", "XF TRANS SARL"),
        ("XPOLogistics", "XPOLogistics"),
        ("Y.A LOGISTIC SARL", "Y.A LOGISTIC SARL"),
        ("YAKINE TRANS", "YAKINE TRANS"),
        ("YARA TRANS", "YARA TRANS"),
        ("YELLOW 8 BLUE", "YELLOW 8 BLUE"),
        ("Z.M LOGISTIC S.A.R.L D'AU", "Z.M LOGISTIC S.A.R.L D'AU"),
        ("ZABIR TRANS", "ZABIR TRANS"),
        ("ZIEGLER MAROC", "ZIEGLER MAROC"),
        ("ZOLO TRANS", "ZOLO TRANS"),
        ("TRANS NUGAR", "TRANS NUGAR"),
        ("TRANS PADRE DAMIAN SL", "TRANS PADRE DAMIAN SL"),
        ("TRANS PARTOUT", "TRANS PARTOUT"),
        ("TRANS RIBAROJA", "TRANS RIBAROJA"),
        ("TRANS SERVICES LINE", "TRANS SERVICES LINE"),
        ("TRANS SESE", "TRANS SESE"),
        ("TRANS UNIVERS", "TRANS UNIVERS"),
        ("TRANS WORLD LOGISTIC CARGO", "TRANS WORLD LOGISTIC CARGO"),
        ("TRANSALIAS", "TRANSALIAS"),
        ("TRANSAMIGOS", "TRANSAMIGOS"),
        ("TRANSBARCELONA", "TRANSBARCELONA"),
        ("TRANSBENSO", "TRANSBENSO"),
        ("TRANS-BEYYAD LOGISTIGUE", "TRANS-BEYYAD LOGISTIGUE"),
        ("TRANSDIR MAROC", "TRANSDIR MAROC"),
        ("TRANSDOR", "TRANSDOR"),
        ("TRANSERVICE INTERNATIONAL", "TRANSERVICE INTERNATIONAL"),
        ("TRANSFARO", "TRANSFARO"),
        ("TRANSFRIMAR", "TRANSFRIMAR"),
        ("TRANSGLORY", "TRANSGLORY"),
        ("TRANSIRINE", "TRANSIRINE"),
        ("TRANSIT JALAL", "TRANSIT JALAL"),
        ("TRANSIT TRUST", "TRANSIT TRUST"),
        ("TRANSLUISA", "TRANSLUISA"),
        ("TRANSMANGRI", "TRANSMANGRI"),
        ("TRANSMEL", "TRANSMEL"),
        ("TRANSMORO.SL", "TRANSMORO.SL"),
        ("TRANSNOUR", "TRANSNOUR"),
        ("TRANSPORT BENNASSER", "TRANSPORT BENNASSER"),
        ("TRANSPORT BOLIPESK", "TRANSPORT BOLIPESK"),
    ],string="Transporteur")